// Secure bridge: exposes a tiny, explicit API to the renderer.
const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("api", {
  getConfig: () => ipcRenderer.invoke("config:get"),
  startGateway: () => ipcRenderer.invoke("gateway:start"),
  getVersion: () => ipcRenderer.invoke("app:version"),
  stopGateway: () => ipcRenderer.invoke("gateway:stop"),
  restartGateway: () => ipcRenderer.invoke("gateway:restart"),
  importAccount: (name, lang) => ipcRenderer.invoke("account:import", { name, lang }),
  importAccountText: (name, cookies, lang) => ipcRenderer.invoke("account:importText", { name, cookies, lang }),
  importFacebook: (name, line) => ipcRenderer.invoke("account:importFacebook", { name, line }),
  onFbStep: (cb) => ipcRenderer.on("account:fbStep", (_e, data) => cb(data)),
  importFacebookElectron: (name, line, lang) => ipcRenderer.invoke("account:importFacebookElectron", { name, line, lang }),
  loginProfile: (name, lang) => ipcRenderer.invoke("account:login", { name, lang }),
  loginElectron: (name, lang) => ipcRenderer.invoke("account:loginElectron", { name, lang }),
  clearCookies: (name) => ipcRenderer.invoke("account:clearCookies", { name }),
  deleteAccount: (name) => ipcRenderer.invoke("account:delete", { name }),
  fetchGenerate: (opts) => ipcRenderer.invoke("video:fetchGenerate", opts),
  onFetchStep: (cb) => ipcRenderer.on("video:fetchStep", (_e, data) => cb(data)),
  setProxy: (name, proxy) => ipcRenderer.invoke("account:setProxy", { name, proxy }),
  getProxy: (name) => ipcRenderer.invoke("account:getProxy", { name }),
  getGlobalProxy: () => ipcRenderer.invoke("proxy:getGlobal"),
  setGlobalProxy: (proxy) => ipcRenderer.invoke("proxy:setGlobal", { proxy }),
  testProxy: (proxy) => ipcRenderer.invoke("proxy:test", { proxy }),
  getProxyLane: () => ipcRenderer.invoke("proxy:lane"),
  rotateProxy: () => ipcRenderer.invoke("proxy:rotate"),
  getRemote: () => ipcRenderer.invoke("remote:get"),
  setRemote: (base, apiKey, adminKey) => ipcRenderer.invoke("remote:set", { base, apiKey, adminKey }),
  testRemote: (base, apiKey, adminKey) => ipcRenderer.invoke("remote:test", { base, apiKey, adminKey }),
  saveVideo: (url) => ipcRenderer.invoke("video:save", { url }),
  openDownloads: () => ipcRenderer.invoke("open:downloads"),
  openLogs: () => ipcRenderer.invoke("open:logs"),
  getAccountsDir: () => ipcRenderer.invoke("account:getAccountsDir"),
  chooseAccountsDir: () => ipcRenderer.invoke("account:chooseAccountsDir"),
  openAccountsDir: () => ipcRenderer.invoke("open:accountsDir"),
  getVideoDir: () => ipcRenderer.invoke("video:getDir"),
  removeWatermark: (file) => ipcRenderer.invoke("video:removeWatermark", { file }),
  verifyAll: (names) => ipcRenderer.invoke("account:verifyAll", names),
  setConcurrency: (send, login) => ipcRenderer.invoke("config:setConcurrency", { send, login }),
  setSubmitGap: (minSec, maxSec) => ipcRenderer.invoke("config:setSubmitGap", { minSec, maxSec }),
  notify: (title, body) => ipcRenderer.invoke("app:notify", { title, body }),
  getAutoRetry: () => ipcRenderer.invoke("config:getAutoRetry"),
  setAutoRetry: (on) => ipcRenderer.invoke("config:setAutoRetry", { on }),
  getOneNick: () => ipcRenderer.invoke("config:getOneNick"),
  setOneNick: (on, nicksPerIp, parallelPerIp) => ipcRenderer.invoke("config:setOneNick", { on, nicksPerIp, parallelPerIp }),
  getSubmitMode: () => ipcRenderer.invoke("config:getSubmitMode"),
  setSubmitMode: (mode) => ipcRenderer.invoke("config:setSubmitMode", { mode }),
  chooseVideoDir: () => ipcRenderer.invoke("video:chooseDir"),
  tailLogs: (n) => ipcRenderer.invoke("logs:tail", n),
  licenseStatus: () => ipcRenderer.invoke("license:status"),
  activateLicense: (key) => ipcRenderer.invoke("license:activate", { key }),
  quitApp: () => ipcRenderer.invoke("app:quit"),
  openConversation: (name, conversationId) => ipcRenderer.invoke("dola:openConversation", { name, conversationId }),
});

